/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cornucopia_HelloJni */

#ifndef _Included_com_cornucopia_HelloJni
#define _Included_com_cornucopia_HelloJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cornucopia_HelloJni
 * Method:    accessMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_cornucopia_HelloJni_accessMethod
  (JNIEnv *, jobject);

/*
 * Class:     com_cornucopia_HelloJni
 * Method:    accessStaticMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_cornucopia_HelloJni_accessStaticMethod
  (JNIEnv *, jclass);

/*
 * Class:     com_cornucopia_HelloJni
 * Method:    accessConstructor
 * Signature: ()Ljava/util/Date;
 */
JNIEXPORT jobject JNICALL Java_com_cornucopia_HelloJni_accessConstructor
  (JNIEnv *, jobject);

/*
 * Class:     com_cornucopia_HelloJni
 * Method:    chinesChars
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cornucopia_HelloJni_chinesChars
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
