/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cornucopia_HelloJni */

#ifndef _Included_com_cornucopia_HelloJni
#define _Included_com_cornucopia_HelloJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cornucopia_HelloJni
 * Method:    get
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cornucopia_HelloJni_get
  (JNIEnv *, jobject);

/*
 * Class:     com_cornucopia_HelloJni
 * Method:    set
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_cornucopia_HelloJni_set
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
